#!/bin/bash
set -e

if ! docker >/dev/null 2>&1 ; then
  echo "
I can't find the docker command.

To install Docker, visit https://www.docker.com/community-edition
"
  exit 1
fi

run_docker () {
    # Run a command inside a transient container.
    #
    # We need to get data out of the container, so we mount generated_docs
    # in place.
    #
    # Currently, ssh keys need to exist in $HOME/.ssh/ to be available.
    docker run -it --rm --init \
	   -v "$(pwd)/generated_docs:/work/streisand/generated_docs" \
	   -v "$HOME/.ssh:/root/.ssh" \
	   streisand-builder "$@"
}

echo
echo "NOTE: Your chosen ssh key must be in $HOME/.ssh/."
echo

run_docker "$@"
