#!/usr/bin/env bash

echo
echo -e "\033[38;5;255m\033[48;5;234m\033[1m  S T R E I S A N D  \033[0m"
echo

required_ansible_version="2.0.1.0"

if [[ "$(ansible --version | grep -oe '2\(.[0-9]\)*')" < $required_ansible_version ]]
then
    echo "Ansible $required_ansible_version or higher is required."
    exit -1;
fi

echo -n "Which provider are you using?
  1. Amazon
  2. DigitalOcean
  3. Google
  4. Linode
  5. Rackspace
: "

read reply

case "$reply" in
  1) echo; echo; ansible-playbook playbooks/amazon.yml;;
  2) echo; echo; ansible-playbook playbooks/digitalocean.yml;;
  3) echo; echo; ansible-playbook playbooks/google.yml;;
  4) echo; echo; ansible-playbook playbooks/linode.yml;;
  5) echo; echo; ansible-playbook playbooks/rackspace.yml;;
esac
