#!/usr/bin/env bash

echo
echo -e "\033[1;97;100m  S T R E I S A N D  \033[0m"
echo

echo -n "Which provider are you using?
  1. Amazon
  2. DigitalOcean
  3. Linode
  4. Rackspace
: "

read reply

case "$reply" in
  1) echo; echo; ansible-playbook playbooks/amazon.yml;;
  2) echo; echo; ansible-playbook playbooks/digitalocean.yml;;
  3) echo; echo; ansible-playbook playbooks/linode.yml;;
  4) echo; echo; ansible-playbook playbooks/rackspace.yml;;
esac
