#!/usr/bin/env bash

echo
echo -e "\033[38;5;255m\033[48;5;234m\033[1m  S T R E I S A N D  \033[0m"
echo

if [[ "$(ansible --version | grep -oe '1.\d.\d')" < "1.6" ]]
then
    echo "Ansible version 1.6+ is required."
    exit -1;
fi

echo -n "Which provider are you using?
  1. Amazon
  2. DigitalOcean
  3. Linode
  4. Rackspace
: "

read reply

case "$reply" in
  1) echo; echo; ansible-playbook playbooks/amazon.yml;;
  2) echo; echo; ansible-playbook playbooks/digitalocean.yml;;
  3) echo; echo; ansible-playbook playbooks/linode.yml;;
  4) echo; echo; ansible-playbook playbooks/rackspace.yml;;
esac
